name = "bottleup-youtube-proxy"
main = "src/index.js"
compatibility_date = "2025-11-15"
account_id = "c9ada733f8ab0e49bfadbdbf05b80fe4"

kv_namespaces = [
  { binding = "SEARCH_CACHE", id = "91e334ea5db44132b2f139495e4556ca" }
]

[vars]
# YT_API_KEY is now managed as a secret via `wrangler secret put`